version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  mongo-ui:
    image: mongoclient/mongoclient
    container_name: mongoui
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:examplepassword@mongo:27017

volumes:
  mongo-data:
